---
# Common setup tasks for Kubernetes node

- name: Check available disk space
  shell: df -h / | awk 'NR==2 {print $4}'
  register: available_space
  changed_when: false

- name: Display available space
  debug:
    msg: "Available disk space: {{ available_space.stdout }}"

- name: Set API_PAGER in /etc/environment
  lineinfile:
    path: /etc/environment
    regexp: '^API_PAGER='
    line: 'API_PAGER=""'
    create: yes

- name: Set API_PAGER in user .bashrc
  lineinfile:
    path: "/home/{{ k8s_user }}/.bashrc"
    line: 'export API_PAGER=""'
    insertafter: EOF
    create: yes
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: '0644'

- name: Disable swap immediately
  command: swapoff -a
  changed_when: false

- name: Comment out swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*\sswap\s.*)$'
    replace: '# \1'

- name: Ensure overlay & br_netfilter modules load on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load kernel modules now
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Write Kubernetes sysctl settings
  copy:
    dest: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      vm.swappiness                       = 0
      vm.overcommit_memory                = 1
      vm.panic_on_oom                     = 0
      fs.inotify.max_user_watches         = 524288
      fs.file-max                         = 131072
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system
  changed_when: false

- name: Remove malformed Kubernetes repo file
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Wait for apt/dpkg to become available
  wait_for:
    path: /var/lib/dpkg/lock
    state: absent
    timeout: 300

- name: Refresh APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    lock_timeout: 300

- name: Install system utilities
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: yes
    lock_timeout: 300
