---
# Common setup tasks for Kubernetes node

- name: Force remove apt locks
  shell: |
    rm -f /var/lib/apt/lists/lock
    rm -f /var/lib/dpkg/lock
    rm -f /var/lib/dpkg/lock-frontend
    rm -f /var/cache/apt/archives/lock
    rm -f /var/lib/dpkg/updates/*
    rm -f /var/lib/dpkg/triggers/*
    dpkg --configure -a
    echo "APT locks cleared"
  changed_when: false

- name: Create empty lock files with permissive permissions
  file:
    path: "{{ item }}"
    state: touch
    mode: '0666'
  with_items:
  - /var/lib/dpkg/lock
  - /var/lib/apt/lists/lock
  - /var/lib/dpkg/lock-frontend
  ignore_errors: yes

- name: Check available disk space
  shell: df -h / | awk 'NR==2 {print $4}'
  register: available_space
  changed_when: false

- name: Display available space
  debug:
    msg: "Available disk space: {{ available_space.stdout }}"

- name: Set API_PAGER in /etc/environment
  lineinfile:
    path: /etc/environment
    regexp: '^API_PAGER='
    line: 'API_PAGER=""'
    create: yes

- name: Set API_PAGER in user .bashrc
  lineinfile:
    path: "/home/{{ k8s_user }}/.bashrc"
    line: 'export API_PAGER=""'
    insertafter: EOF
    create: yes
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: '0644'

- name: Disable swap immediately
  command: swapoff -a
  changed_when: false

- name: Comment out swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*\sswap\s.*)$'
    replace: '# \1'

- name: Ensure overlay & br_netfilter modules load on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load kernel modules now
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - overlay
  - br_netfilter

- name: Write Kubernetes sysctl settings
  copy:
    dest: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      vm.swappiness                       = 0
      vm.overcommit_memory                = 1
      vm.panic_on_oom                     = 0
      fs.inotify.max_user_watches         = 524288
      fs.file-max                         = 131072
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system
  changed_when: false

- name: Remove malformed Kubernetes repo file
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

# Replace the problematic wait_for task with a more reliable approach
- name: Check if apt/dpkg is in use
  shell: |
    if lsof /var/lib/dpkg/lock >/dev/null 2>&1 || lsof /var/lib/apt/lists/lock >/dev/null 2>&1; then
      echo "Locks are still held"
      exit 1
    else
      echo "No locks found"
      exit 0
    fi
  register: apt_check
  changed_when: false
  failed_when: false
  retries: 30
  delay: 10
  until: apt_check.rc == 0
  when: not skip_apt_lock_check | default(false)

- name: Refresh APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: yes

- name: Install system utilities
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  register: pkg_install
  retries: 5
  delay: 10
  until: pkg_install is succeeded
